# Generated by Django 4.2.6 on 2023-10-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('friendliness', models.IntegerField(choices=[(1, 'Verylow'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Veryhigh')])),
                ('trainability', models.IntegerField(choices=[(1, 'Verylow'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Veryhigh')])),
                ('sheddingamount', models.IntegerField(choices=[(1, 'Verylow'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Veryhigh')])),
                ('exerciseneeds', models.IntegerField(choices=[(1, 'Verylow'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Veryhigh')])),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('favoritefood', models.CharField(max_length=200)),
                ('favoritetoy', models.CharField(max_length=200)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.breed')),
            ],
        ),
    ]
